### ISSUE TITLE
`SvgCanvas2D` - unexpected behavior of `roundrect` 

### ISSUE THREAD

**Issue by mayorovad** [maxGraph/maxgraph#107]
Hi! 

Had issue with round rectangles in my custom shape not being rendered after calling `roundrect`. 

After looking up sources, I noticed that at the [beginning](https://github.com/maxGraph/maxGraph/blob/02ea6f1ceb398c2a6c08df7ecc52ee3d5efe46cc/packages/core/src/view/canvas/SvgCanvas2D.ts#L1008) of `roundrect` function there is check `if (!this.node) return;` before calling `rect()`. 
```typescript
  roundrect(x: number, y: number, w: number, h: number, dx: number, dy: number) {
    if (!this.node) return;

    this.rect(x, y, w, h);

    ...
   ```
So I'm wondering why it's here. Calling `begin` before `roundrect` seems to fix issue, because `begin()` initialize `node` variable, but `rect()` will initialize it anyway.

**Comment by tbouffard** [comment]
@mayorovad Thanks for filling this issue and the detailled report!

I confirmed the issue that I also detected while configuring the typescript example in this repository in #87 when setting the `isRounded` property to `true` in a class extending `RectangleShape`:
https://github.com/maxGraph/maxGraph/blob/02ea6f1ceb398c2a6c08df7ecc52ee3d5efe46cc/packages/ts-example/src/custom-shapes.ts#L30-L34


In the original mxGraph code, there isn't the extra `this.node` check which is currently implemented in maxGraph.
See https://github.com/jgraph/mxgraph/blob/v4.2.2/javascript/src/js/util/mxSvgCanvas2D.js#L1002-L1011

As explained in the description of the issue, the node property is set when calling the `rect` method: 
https://github.com/maxGraph/maxGraph/blob/02ea6f1ceb398c2a6c08df7ecc52ee3d5efe46cc/packages/core/src/view/canvas/SvgCanvas2D.ts#L1007-L1010

https://github.com/maxGraph/maxGraph/blob/02ea6f1ceb398c2a6c08df7ecc52ee3d5efe46cc/packages/core/src/view/canvas/SvgCanvas2D.ts#L993-L1002


The change was introduced in 0453da274fbbeba4b7a457daec1cd9ad6db4abe0. I also noticed that this commit introduced other changes like the one in the `roundrect` in methods
- updateStrokeAttributes
- updateFill

The commit also added `if (!this.root) return;` in the following methods
- getSvgGradient
- text

@junsikshim do you remember why the checks were added? I don't find any information in the commit log related to the addition.

AFAIK, we didn't change the way the SVG canvas is working compared to the original mxGraph implementation. So I suggest to try to remove all these changes and check the result in the examples.

**Comment by junsikshim** [comment]
@tbouffard I added those null checks in order to resolve TS errors, but apparently I didn't think it through.
I've created a PR #108 to fix them. It's not the prettiest solution and it might suffer from some undiscovered null situations, but it won't break at least.

Thank you for the issue report!

**Comment by tbouffard** [comment]
@junsikshim thanks for the quick feedback, the explanations and the fix!
I haven't seen the risk of TS errors as the `root` and `node` properties are defined as nullable.
