### ISSUE TITLE
Cells are still rendering after removing using `removeCells` method of `Graph`

### ISSUE THREAD

**Issue by mayorovad** [maxGraph/maxgraph#114]
Hello! 

After calling `removeCells` on graph, cells are still rendered, but cell drag logic is broken.

I added PR #113 to fix story `Visibility`, which is also has code to test cells removal. 
I will try to find issue, but with my current level of understanding codebase it`s seems to be difficult.

**Comment by lukasonokoleg** [comment]
@mayorovad  - I am not sure if it will help, but as workaround I've done following...

```
const CELLS = ....

graph.removeCells(CELLS);
for (let cell of CELLS) {
  graph.view.clear(cell, true, false);
}
```

Seems to work fine. But it is not a fix - just a workarround.

**Comment by mayorovad** [comment]
Hi @lukasonokoleg ! Thanks for workarround! Also, have you seen #115? It may be real fix, i think.
