### ISSUE TITLE
Add `eslint` and fix some side-effects

### ISSUE THREAD

**Issue by mayorovad** [maxGraph/maxgraph#122]
Hi! 

After looking at code for a little longer, it's seems that there are many introduced side-effects, which will be **VERY** tiring to find with the naked eye 👁️ . What do you think about adding [eslint](https://github.com/eslint/eslint) and looking what`s up? After linting with simple set of rules, there is indeed some interesting places, which can lead to bugs/side-effects, and also some code-style inconsistencies.

For example in `addTextBackground` of svg canvas:
https://github.com/maxGraph/maxGraph/blob/02ea6f1ceb398c2a6c08df7ecc52ee3d5efe46cc/packages/core/src/view/canvas/SvgCanvas2D.ts#L1755-L1756

There is checks for `null`, but when porting, `null` initialization replaced with `NONE` value, so this check will never work again, which lead to calling very time-consuming code of `addTextBackground`.
https://github.com/maxGraph/maxGraph/blob/02ea6f1ceb398c2a6c08df7ecc52ee3d5efe46cc/packages/core/src/types.ts#L232-L233
https://github.com/maxGraph/maxGraph/blob/02ea6f1ceb398c2a6c08df7ecc52ee3d5efe46cc/packages/core/src/view/canvas/AbstractCanvas2D.ts#L166-L167

But with right set of rules `eslint` is able to find it and scream warning `Unnecessary conditional, the types have no overlap`

Will be happy to make PR with `eslint` configured, if you interested :)

**Comment by tbouffard** [comment]
Hi @mayorovad and thanks for all your recent contributions.
Introducing eslint will be great.

**Comment by tbouffard** [comment]
Fixed by #133
