### ISSUE TITLE
Graph.importCells should have optional x/y args in ts-signature

### ISSUE THREAD

**Issue by Neschastje** [maxGraph/maxgraph#148]
Hello.
Current signature of importCells is:
`importCells: (cells: Cell[], dx: number, dy: number, target?: Cell | null, evt?: MouseEvent | null, mapping?: any) => Cell[];`
In the "Drag Source" example importCells being called inside DropHandler for gestureUtils.makeDraggable. It feels like its common case and current implementation makes you write something like:
```
const xNum: number = x || 0;
const yNum: number = y || 0;
```
in every TypeScript DropHandler implementation.
Original mxGraph [docs](https://jgraph.github.io/mxgraph/docs/js-api/files/view/mxGraph-js.html#mxGraph.importCells) says that default of x/y args in importCells is 0, so my suggestion that x and y should be optional in it's signature.

**Comment by borisvorobev** [comment]
@Kozyyy  I had the same issue. You can create a pull request for fixing this issue.

**Comment by tbouffard** [comment]
I agree with the conclusions.

In addition, `importCells` only calls `moveCells` which has the following signature which is consistent with the proposal described in this issue:
```typescript
moveCells(
    cells,
    dx = 0,
    dy = 0,
    clone = false,
    target = null,
    evt = null,
    mapping = {}
  )
```

I guess the issue in maxGraph comes from `typed-mxgraph` (it has been used at starting point for types in maxGraph) that also marks the `dx` and `dy` parameters as mandatory https://github.com/typed-mxgraph/typed-mxgraph/blob/v1.0.7/lib/view/mxGraph.d.ts#L2115-L2127
