### ISSUE TITLE
Stories with mathUtils.convertPoint

### ISSUE THREAD

**Issue by f-wrobel** [maxGraph/maxgraph#164]
### Discussed in https://github.com/maxGraph/maxGraph/discussions/161

In several stories, there is a reference to `mathUtils.convertPoint` which apparently is wrong, becasue `convertPoint` is in `styleUtils`.
Stories affected:
```
AutoLayout.stories.js
Boundary.stories.js
ContextIcons.stories.js
Drop.stories.js
EdgeTolerance.stories.js
Editing.stories.js
```
Example: https://github.com/maxGraph/maxGraph/blob/v0.1.0/packages/html/stories/AutoLayout.stories.js#L193-L197

**Comment by tbouffard** [comment]
@f-wrobel thanks for creating this issue.

Do you want to create a Pull Request to solve the problem yourself?
If you need help, let me know.

**Comment by f-wrobel** [comment]
@tbouffard, I think I have to check if this is a simple fix or the stories are more outdated.
