### ISSUE TITLE
Decoding XML breaks when code is minified

### ISSUE THREAD

**Issue by urdeveloper** [maxGraph/maxgraph#169]
When migrating from mxGraph to maxGraph I realized decoding XML doesn't work if the final code is minified. This is because decoding XML elements and finding a corresponding decoder is based on the constructor name. When code is minified, those constructor names are not same as the original ones (for example, GraphDataModel, Cell, ...). 
To fix this I believe the decoders and codec registry need to be refactored  to not rely on constructor names anymore.
Please let me know if this a correct observation, then I can start working on a PR to address the issue.
Thanks!

**Comment by ksteuer** [comment]
Hi! I found the same issue recently. Did you do any deeper analysis of what is needed to be done?

**Comment by tbouffard** [comment]
Hi
The analysis seems correct. Strangely, the `CodecRegistry` is the only place where the references are directly stored.
All other registries use a mapping between a name and a Constructor.
I suppose we could do the same here.

@urdeveloper if you want to contribute a fix for the issue describe here, I first suggest we make the examples involving the Codec work.
The original mxGraph Codec example has not been migrated (https://github.com/maxGraph/maxGraph/blob/v0.1.0/packages/html/stories/stashed/Codec.js) and the IO examples is broken (#88 could help)
IMHO, we should first provide a PR to fix the examples. This will provide a way to quickly check that everything work fine before and after the fix.

Notice that the XML loading from the original mxGraph model file is incomplete, in particular after the switch for the style definition from a string form to the object form. See also #102 and #125
We can manage this later.

**Comment by tbouffard** [comment]
I have just created a PR that introduces automatic tests for model encoding/decoding #183.
This will also helps to implement refactoring related to the problems described here.

**Comment by g136660** [comment]
do you have any workaround for this?

**Comment by tbouffard** [comment]
You may give a try to the alias: https://github.com/maxGraph/maxGraph/blob/487e4b767efe537eecc6a09ed8be17bdcdce52b4/packages/core/src/serialization/CodecRegistry.ts#L83-L89

**Comment by tbouffard** [comment]
ℹ️ It is possible to reproduce the error with the `DynamicLoading` story. See #296.

**Comment by tbouffard** [comment]
I have created #309 that makes the XML import/decode work for Graph Data Model objects only and it is included in version `0.7.0`.
It also partially fixes the export/encode for model objects. It has some limitations, see for example #327.

This PR doesn't change how codecs are stored and retrieved internally. With the example introduced in this PR and existing automatic tests, this should help people who wants to contribute a more complete fix to apply it to all codecs and not only to codecs used to manage the Model objects.

**Comment by tbouffard** [comment]
I am marking this issue as closed and fixed in v0.7.0.
It fixes most problems related to the model codecs which was the scope mentioned in the description of this issues.

Other codecs may have the same problems.
Please create a dedicated issue if this is the case, and provide code, xml output, .... to reproduce the problem.
