### ISSUE TITLE
Error encountered when running project on new Windows computer

### ISSUE THREAD

**Issue by cd-yang** [maxGraph/maxgraph#188]
I encountered the following error when running the project on a new Windows computer. My node and npm versions are v18.15.0 and 6.14.17 respectively.

> PS C:\Users\SE-YCD\Desktop\maxGraph> npm run dev
> maxgraph@0.1.0 dev C:\Users\SE-YCD\Desktop\maxGraph
> node ./scripts/dev
? Select a package to run. @maxgraph/html
Running 'npx lerna run dev --stream --scope @maxgraph/html'...
npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm WARN config shrinkwrap Use the --package-lock setting instead.
npm WARN config tmp This setting is no longer used.  npm stores temporary files 
in a special
npm WARN config location in the cache, and they are managed by
npm WARN config     [`cacache`](http://npm.im/cacache).
info cli using local version of lerna
lerna notice cli v4.0.0
lerna notice filter including "@maxgraph/html"
lerna info filter [ '@maxgraph/html' ]
lerna info Executing command in 1 package: "npm run dev"
@maxgraph/html: npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
@maxgraph/html: npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
@maxgraph/html: npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
@maxgraph/html: npm WARN config `--include=optional` to include them.
@maxgraph/html: npm WARN config
@maxgraph/html: npm WARN config     Default value does install optional deps unless otherwise omitted.
@maxgraph/html: npm WARN config shrinkwrap Use the --package-lock setting instead.
@maxgraph/html: npm WARN config tmp This setting is no longer used.  npm stores 
temporary files in a special
@maxgraph/html: npm WARN config location in the cache, and they are managed by  
@maxgraph/html: npm WARN config     [`cacache`](http://npm.im/cacache).
@maxgraph/html: > @maxgraph/html@0.0.0 dev C:\Users\SE-YCD\Desktop\maxGraph\packages\html
@maxgraph/html: > start-storybook -p 8901
@maxgraph/html: info @storybook/html v6.5.16
@maxgraph/html: info 
@maxgraph/html: info => Loading presets
@maxgraph/html: info => Serving static files from ./.\public at /
@maxgraph/html: info Addon-docs: using MDX1
@maxgraph/html: info => Using implicit CSS loaders
@maxgraph/html: info => Loading custom Webpack config (full-control mode).
@maxgraph/html: (node:16852) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
@maxgraph/html: you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.
@maxgraph/html: See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
@maxgraph/html: (Use `node --trace-deprecation ...` to show where the warning was created)
@maxgraph/html:  [webpack.Progress] 0% compiling
@maxgraph/html:  [webpack.Progress] 10% building 0/0 modules 0 active        
@maxgraph/html:  [webpack.Progress] 10% building 0/1 modules 1 active multi C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\core-client\dist\esm\globals\polyfills.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\core-client\dist\esm\globals\globals.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\webpack-hot-middleware\client.js?reload=true&quiet=false&noInfo=undefined C:\Users\SE-YCD\Desktop\maxGraph\packages\html\storybook-init-framework-entry.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\html\dist\esm\client\preview\config-generated-config-entry.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\html\dist\esm\client\docs\config-generated-config-entry.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-links\preview.js-generated-config-entry.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-docs\preview.js-generated-config-entry.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-actions\preview.js-generated-config-entry.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-backgrounds\preview.js-generated-config-entry.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-measure\preview.js-generated-config-entry.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-outline\preview.js-generated-config-entry.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\.storybook\preview.js-generated-config-entry.js C:\Users\SE-YCD\Desktop\maxGraph\packages\html\generated-stories-entry.js@maxgraph/html: <s> [webpack.Progress] 10% building 1/1 modules 0 active 
@maxgraph/html: <s> [webpack.Progress] 10% building 1/2 modules 1 active C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-docs\preview.js-generated-config-entry.js
@maxgraph/html: <s> [webpack.Progress] 10% building 1/3 modules 2 active C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-actions\preview.js-generated-config-entry.js
@maxgraph/html: <s> [webpack.Progress] 10% building 1/4 modules 3 active C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-backgrounds\preview.js-generated-config-entry.js
@maxgraph/html: <s> [webpack.Progress] 10% building 1/5 modules 4 active C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-links\preview.js-generated-config-entry.js
@maxgraph/html: <s> [webpack.Progress] 10% building 1/6 modules 5 active C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-measure\preview.js-generated-config-entry.js
@maxgraph/html: <s> [webpack.Progress] 10% building 1/7 modules 6 active C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\addon-outline\preview.js-generated-config-entry.js
@maxgraph/html: node:internal/crypto/hash:71
@maxgraph/html:   this[kHandle] = new _Hash(algorithm, xofLen);
@maxgraph/html:                   ^
@maxgraph/html: Error: error:0308010C:digital envelope routines::unsupported    
@maxgraph/html:     at new Hash (node:internal/crypto/hash:71:19)
@maxgraph/html:     at Object.createHash (node:crypto:133:10)
@maxgraph/html:     at module.exports (C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\util\createHash.js:135:53)
@maxgraph/html:     at NormalModule._initBuildHash (C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\NormalModule.js:417:16)
@maxgraph/html:     at handleParseError (C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\NormalModule.js:471:10)
@maxgraph/html:     at C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\NormalModule.js:503:5   
@maxgraph/html:     at C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\@storybook\builder-webpack4\node_modules\webpack\lib\NormalModule.js:358:12  
@maxgraph/html:     at C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\loader-runner\lib\LoaderRunner.js:373:3
@maxgraph/html:     at iterateNormalLoaders (C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
@maxgraph/html:     at C:\Users\SE-YCD\Desktop\maxGraph\packages\html\node_modules\loader-runner\lib\LoaderRunner.js:205:4 {
@maxgraph/html:   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
@maxgraph/html:   library: 'digital envelope routines',
@maxgraph/html:   reason: 'unsupported',
@maxgraph/html:   code: 'ERR_OSSL_EVP_UNSUPPORTED'
@maxgraph/html: }
@maxgraph/html: Node.js v18.15.0
@maxgraph/html: npm ERR! code ELIFECYCLE
@maxgraph/html: npm ERR! errno 1
@maxgraph/html: npm ERR! @maxgraph/html@0.0.0 dev: `start-storybook -p 8901`    
@maxgraph/html: npm ERR! Exit status 1
@maxgraph/html: npm ERR!
@maxgraph/html: npm ERR! Failed at the @maxgraph/html@0.0.0 dev script.
@maxgraph/html: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@maxgraph/html: npm ERR! A complete log of this run can be found in:
@maxgraph/html: npm ERR!     C:\Users\SE-YCD\AppData\Roaming\npm-cache\_logs\2023-03-29T06_59_41_338Z-debug.log
lerna ERR! npm run dev exited 1 in '@maxgraph/html'

**Comment by cd-yang** [comment]
Solved by setting `NODE_OPTIONS="--openssl-legacy-provider"` [source](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported)

**Comment by tbouffard** [comment]
Hi, the GitHub workflows run with node 16 without any problem on windows.
The nose version requirement is probably missing in n thé README.
I remember that in the past, some users had the same issue as yours with node 17.
