### ISSUE TITLE
Uncaught TypeError in StyleUtils function getCurrentStyle()

### ISSUE THREAD

**Issue by sdgoldstein** [maxGraph/maxgraph#208]
During mouse events, I'm observing Uncaught TypeErrors in StyleUtils function getCurrentStyle():

`
export const getCurrentStyle = (element: HTMLElement) => {
  return element ? window.getComputedStyle(element, '') : null;
};
`

This appears to be happening when the argument to the function is a document fragment rather than an HTMLElement.  The document fragment is a ShadowDom element.

**Comment by tbouffard** [comment]
This seems to duplicate #68.

**Comment by sdgoldstein** [comment]
Yes, it is.  Apologies, I had searched the issue list, and that one didn't come up.  Thanks for the quick reply.

**Comment by tbouffard** [comment]
@sdgoldstein the issue is fixed and the fix will be included in the next release.

**Comment by sdgoldstein** [comment]
Fantastic!  Thank you for addressing this!

**Comment by tbouffard** [comment]
https://github.com/maxGraph/maxGraph/releases/tag/v0.3.0 is available.
Fill free to open a new issue if problems still exist when integrating `maxGraph` in Web Components.
