### ISSUE TITLE
How to load from string?

### ISSUE THREAD

**Issue by tennessine** [maxGraph/maxgraph#221]
```
<mxGraphModel dx="1502" dy="926" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1920" pageHeight="1200" math="0" shadow="0"><root><mxCell id="0"/><mxCell id="1" parent="0"/><mxCell id="2Ija7sB8CSz23ppRtK8d-5" value="PostgreSQL" style="rounded=0;whiteSpace=wrap;html=1;fillColor=#dae8fc;strokeColor=#6c8ebf;fontStyle=1;fontSize=27;" parent="1" vertex="1"><mxGeometry x="650" y="430" width="210" height="80" as="geometry"/></mxCell></root></mxGraphModel>
```

How to render the string?

**Comment by tbouffard** [comment]
Hi,
Loading legacy mxGraph model from xml is currently not supported.
Even loading the model with the new maxGraph format is not fully working. See #169, #178, #197, ...

Next time you have a question, can you please create it in the [discussions](https://github.com/maxGraph/maxGraph/discussions/categories/q-a) instead? This will keep the issues list clean.
Thx
