### ISSUE TITLE
Can't download package from npm

### ISSUE THREAD

**Issue by Anthony-Wratpor** [maxGraph/maxgraph#227]
Hello,

When doing the command npm install @maxgraph/core i have the following error :

npm ERR! Cannot read properties of null (reading 'matches')

[2023-07-18T08_33_00_990Z-debug-0.log](https://github.com/maxGraph/maxGraph/files/12078186/2023-07-18T08_33_00_990Z-debug-0.log)

It's not a brand new angular application but i just did a npm update before this, maybe the problem is from there.

**Comment by tbouffard** [comment]
Hi @Anthony-Wratpor 
I am not aware of issues with the @maxgraph/core package. https://github.com/maxGraph/maxgraph-integration-examples uses the npm package without error (latest 0.3.0 and previous versions in the past). This is automatically tested in fresh environments using GitHub Actions.

According the provided logs, here is your environment
- OS: windows
- node v18.13.0
- npm  v8.19.3


The error is generated by the npm cli. Did you try with a more recent version of the npm cli like v9?
You may also try a fresh `npm clean-install`
```
4640 verbose stack TypeError: Cannot read properties of null (reading 'matches')
4640 verbose stack     at Link.matches (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\node.js:1114:41)
```

**Comment by Anthony-Wratpor** [comment]
Thanks for the fast answer ! 

You are right it was my bad, in this project i used pnpm instead of npm, i just did a pnpm install and it works now, sorry for bothering you with this, i'm closing this issue.

Thank you very much !

**Comment by tbouffard** [comment]
I'm glad to hear you've solved your problem. And that there's no problem with the package 😄
