### ISSUE TITLE
Getting error on circular dependency using HierarchicalLayout

### ISSUE THREAD

**Issue by Franz-Ritter** [maxGraph/maxgraph#231]
Hi, 
I try to migrate the mxGraph library to the maxGraph library in my project, and receive an error on a use case which used to work on the old mxGraph library.

When I try to create a HierarchicalLayout which contains a circular dependency, I receive an error:

TypeError: Cannot read properties of undefined (reading 'push')
    at http://localhost:8901/main.iframe.bundle.js:69642:34
    at GraphHierarchyModel.dfs (http://localhost:8901/main.iframe.bundle.js:69729:11)
    at GraphHierarchyModel.dfs (http://localhost:8901/main.iframe.bundle.js:69738:18)
    at GraphHierarchyModel.visit (http://localhost:8901/main.iframe.bundle.js:69700:20)
    at GraphHierarchyModel.fixRanks (http://localhost:8901/main.iframe.bundle.js:69640:12)
    at HierarchicalLayout.layeringStage (http://localhost:8901/main.iframe.bundle.js:62750:13)
    at HierarchicalLayout.run (http://localhost:8901/main.iframe.bundle.js:62543:14)
    at http://localhost:8901/main.iframe.bundle.js:62281:16
    at GraphDataModel.batchUpdate (http://localhost:8901/main.iframe.bundle.js:20316:9)
    at HierarchicalLayout.execute (http://localhost:8901/main.iframe.bundle.js:62280:13)
    
 
Let me provide you a simple setup scenario, which is based on the example in packages\html\stories\HierarchicalLayout.stories.js:

    const v1 = graph.insertVertex(parent, null, '1', 0, 0, 80, 30);
    const v2 = graph.insertVertex(parent, null, '2', 0, 0, 80, 30);
    const v3 = graph.insertVertex(parent, null, '3', 0, 0, 80, 30);
    const v4 = graph.insertVertex(parent, null, '4', 0, 0, 80, 30);
    const v5 = graph.insertVertex(parent, null, '5', 0, 0, 80, 30);
    const v6 = graph.insertVertex(parent, null, '6', 0, 0, 80, 30);
    const v7 = graph.insertVertex(parent, null, '7', 0, 0, 80, 30);
    const v8 = graph.insertVertex(parent, null, '8', 0, 0, 80, 30);
    const v9 = graph.insertVertex(parent, null, '9', 0, 0, 80, 30);

    const e1 = graph.insertEdge(parent, null, '', v1, v2);
    const e2 = graph.insertEdge(parent, null, '', v2, v3);
    const e3 = graph.insertEdge(parent, null, '', v3, v4);
    const e4 = graph.insertEdge(parent, null, '', v4, v5);
    const e5 = graph.insertEdge(parent, null, '', v5, v3);
    const e6 = graph.insertEdge(parent, null, '', v5, v6);
    const e7 = graph.insertEdge(parent, null, '', v6, v7);
    const e8 = graph.insertEdge(parent, null, '', v7, v8);
    const e9 = graph.insertEdge(parent, null, '', v8, v9);
    
Running the HierarchicalLayout#execute() method results in the exception above.
I was already able to identify, that the rankList which is created on the startup seems not to identify the correct layer depth, which end at layer 3. However, I was expecting the same behaviour as in the legacy code: https://github.com/jgraph/mxgraph/blob/master/javascript/src/js/layout/hierarchical/mxHierarchicalLayout.js. , which I can confirm can render a hierarchical graph with the same edge configuration as above.

Can some one confirm, that this is a bug?

**Comment by Franz-Ritter** [comment]
I believe I've identified the problem causing the issue with HierarchicalLayout. The layout builds an internal graph using the MinimumCycleRemover algorithm (source: [HierarchicalLayout.ts](https://github.com/maxGraph/maxGraph/blob/e25fd447be9ff3c02b877928ed17a615a4d77896/packages/core/src/view/layout/HierarchicalLayout.ts#L515)), which traverses the graph to identify and resolve cycles.

The problem arises during the ancestor check (source: [MinimumCycleRemover.ts](https://github.com/maxGraph/maxGraph/blob/e25fd447be9ff3c02b877928ed17a615a4d77896/packages/core/src/view/layout/hierarchical/MinimumCycleRemover.ts#L119)). The current implementation uses the isAncestor method of the Cell class, which is a superclass of GraphHierarchyNode. The mxGraph node's isAncestor method relies on a hash code, while the maxGraph solution identifies ancestors by traversing parents (source: [Cell.ts](https://github.com/maxGraph/maxGraph/blob/e25fd447be9ff3c02b877928ed17a615a4d77896/packages/core/src/view/cell/Cell.ts#L674)).

This leads to an issue because the parent value of the cell is not set (null) at this point, causing the check to fail. Using the original isAncestor method of GraphHierarchyNode should resolve the problem. I noticed that it is currently commented out in the code (source: [GraphHierarchyNode.ts](https://github.com/maxGraph/maxGraph/blob/e25fd447be9ff3c02b877928ed17a615a4d77896/packages/core/src/view/layout/datatypes/GraphHierarchyNode.ts#L153C8-L153C8)).

@tbouffard, could you please confirm my assumptions?

**Comment by tbouffard** [comment]
Hi @Franz-Ritter 
I am not able to review this issue for now.
But if you can reproduce it with an unit test and fix the problem, feel free to create a Pull Request. I will review it in mid-August.

**Comment by Franz-Ritter** [comment]
@tbouffard, thanks. I opened a PR. Let me know if you miss something.

**Comment by tbouffard** [comment]
@Franz-Ritter thanks for the detailed analysis.
At last, I've been able to take the time to look into this problem.

The problem was unintentionally introduced during the initial refactoring of the mxGraph code in 413796ad322ddfeb9228f9e4913a2d80b196fa0b.
The idea of the author was to remove an useless comment but they left an extra `/**` behind which commented the `isAncestor` method 😮 So, I guess removing this extra comment instruction will fix the issue 😸 

![Screenshot 2023-09-14 at 10-55-52 Finish converting core to ts JSDoc conversion consistency conventio… · maxGraph_maxGraph@413796a](https://github.com/maxGraph/maxGraph/assets/27200110/dd07a50c-93f3-481e-bb1a-9b149b141bd2)


You can see it in https://github.com/maxGraph/maxGraph/commit/413796ad322ddfeb9228f9e4913a2d80b196fa0b#diff-f9061c0a39f67fdf599ffd9378e6866177412b609368793edc0fa940e791e691L157-R139 (warn: very large commit, so the browser has difficulties to display the whole changes) that I found thanks to https://github.com/maxGraph/maxGraph/blame/e25fd447be9ff3c02b877928ed17a615a4d77896/packages/core/src/view/layout/datatypes/GraphHierarchyNode.ts#L151-L154.

**Comment by Franz-Ritter** [comment]
@tbouffard Ah okay, that makes sense. I assumed something like that. I was just not 100% sure if the author wanted to reuse the "other" isAncesotor method. Anyway, I am happy that you find time to apply the fix. The library became quite promising for me. So it might be that, I can provide you some additional feedback in future.

Thanks Again
