### ISSUE TITLE
[Question] How to use the VertexHandler rotationEnabled

### ISSUE THREAD

**Issue by to0simple** [maxGraph/maxgraph#267]
setting
```
VertexHandler.prototype.rotationEnabled = true
```
but didn't work
Could you tell me how to use it

**Comment by tbouffard** [comment]
Hi, can you provide more details about what you try to achieve?
Please also have a look at #83 and at https://github.com/maxGraph/maxGraph/blob/v0.5.0/packages/html/stories/Stencils.stories.js. I don't know if the story work.

**Comment by to0simple** [comment]
In this file(https://github.com/maxGraph/maxGraph/blob/v0.5.0/packages/html/stories/Stencils.stories.js.)
setting rotateEnable = true
![image](https://github.com/maxGraph/maxGraph/assets/23261843/18ad92df-8957-4999-9e89-3d3ee752b1ca)
When I run, I still don't see the rotation
![image](https://github.com/maxGraph/maxGraph/assets/23261843/51ea17c7-dacb-4d65-b4fd-87c4862f3266)

**Comment by tbouffard** [comment]
Hi nobody has worked on this topic so the issue probably still exists.

**Comment by mjankela** [comment]
I would be also curious. While setting "VertexHandler.prototype.rotationEnabled = true" works fine in mxGraph it doesn't work with maxGraph.

**Comment by tbouffard** [comment]
> I would be also curious. While setting "VertexHandler.prototype.rotationEnabled = true" works fine in mxGraph it doesn't work with maxGraph.

Hi @mjankela, this is probably due to the definition of VertexHandler in maxGraph which uses the class construct form

**Comment by tbouffard** [comment]
Hi @to0simple for now, you can use the following workaround:
- provide a custom `VertexHandler` that ignore the `rotationEnabled` property (mimic a `true` value)
- use the custom  `VertexHandler` in a custom implementation of the `Graph` class
- use the custom implementation of the `Graph` class

```typescript
  class CustomVertexHandler extends VertexHandler {
    // the following code is adapted from magraph v0.11.0
    isRotationHandleVisible() {
      const selectionHandler = this.graph.getPlugin(
        'SelectionHandler'
      ) as SelectionHandler;
      const selectionHandlerCheck = selectionHandler
        ? selectionHandler.maxCells <= 0 ||
          this.graph.getSelectionCount() < selectionHandler.maxCells
        : true;

      return (
        this.graph.isEnabled() &&
        // this.rotationEnabled && // this is the original condition
        this.graph.isCellRotatable(this.state.cell) &&
        selectionHandlerCheck
      );
    }
  }

  class CustomGraph extends Graph {
    constructor(container: HTMLElement) {
      super(container);
    }
    createVertexHandler(state: CellState) {
      return new CustomVertexHandler(state);
    }
  }
```

**Comment by tbouffard** [comment]
#480 will provide new ways to enable the rotation. It should be included in the next maxGraph version.

ℹ️ I have notice that there may be an issue with the handles: #482
