### ISSUE TITLE
How to optimize the wiring

### ISSUE THREAD

**Issue by zhangbaojia** [maxGraph/maxGraph#3]
![line](https://user-images.githubusercontent.com/19427334/103116857-db21be00-46a2-11eb-88c2-c70525dae618.png)

How to connect as shown below by default?

![line2](https://user-images.githubusercontent.com/19427334/103117176-330cf480-46a4-11eb-9173-a5578ed626e3.png)

**Comment by zhangbaojia** [comment]
The line cannot be on the graph。thanks！

**Comment by Alsekar** [comment]
I'm interested in this as well, I haven't found any examples that shows how to do this. However  https://github.com/mwangm/mxgraph-manhattan-connector this repository  has the code and seems to be working.

**Comment by tbouffard** [comment]
Closing because of the lack of activity.
For more information about a potential implement of the manhattan connector in maxGraph, see https://github.com/maxGraph/maxGraph/discussions/116.
If you have new question, please open a https://github.com/maxGraph/maxGraph/discussions instead of an issue
