### ISSUE TITLE
PopupMenuHandler.factoryMethod has a wrong type?

### ISSUE THREAD

**Issue by eldonwilliams** [maxGraph/maxgraph#308]
Hello

I am trying to extend `PopupMenuHandler` and override `.factoryMethod`.

Currently, the signature is `.factoryMethod(handler: PopupMenuItem, cell: Cell | null, me: MouseEvent) => void`. However, based on everything I can gather, `handler` should have the type `PopupMenuHandler`.

My code is below, I am using the latest build.

```ts
import { Cell, Graph, PopupMenuHandler, PopupMenuItem } from "@maxgraph/core";

export default class CustomPopupMenuHandler extends PopupMenuHandler {
    constructor(graph: Graph) {
        super(graph);

        this.addItem("Delete", null, function (){});

        // @ts-ignore
        this.factoryMethod = (handler: CustomPopupMenuHandler, cell: Cell, me: MouseEvent) => {
            console.log(handler)
        }
    }
}
```

Thank you,
Eldon

**Comment by tbouffard** [comment]
Hi @eldonwilliams, your conclusions seem correct.

Apparently, the type of the `factoryMethod` property may not have been correctly set in 61648e43.
In mxGraph, it was an `mxPopupMenuHandler`
- https://github.com/typed-mxgraph/typed-mxgraph/blob/v1.0.8/lib/util/mxPopupMenu.d.ts

This should confirmed by checking https://github.com/maxGraph/maxGraph/blob/v0.7.0/packages/html/stories/MenuStyle.stories.js#L168-L169
```javascript
      // Installs context menu
      this.factoryMethod = function (menu, cell, evt) {
        menu.addItem('Item 1', null, function () {
          alert('Item 1');
        });
        menu.addItem('Item 2', null, function () {
          alert('Item 2');
        });
        menu.addSeparator();
```

The handler parameter should be a `MaxPopupMenu` or a `PopupMenuHandler`.

Feel free to provide a PR with a fix. This could be nice to convert the _MenuStyle_ story to TypeScript at the same time.

**Comment by tbouffard** [comment]
See also discussions in #399
