### ISSUE TITLE
Java: Include debug information with compiled code by default

### ISSUE THREAD

**Issue by vuongddang** [maxGraph/maxGraph#32]
Currently, the java libraries are compiled without debug information which makes it impossible for the consumer of the library to debug in case of error. 

To include debug information, update the build.xml and set the property compile.debug to true

```
<property name="compile.debug"       value="true"/>
```

**Comment by tbouffard** [comment]
According to #19, we are not going to keep the java implementation in this repository. In this case, this will not included.

**Comment by vuongddang** [comment]
I see, thanks for your answer.
