### ISSUE TITLE
Errors occur when using encode

### ISSUE THREAD

**Issue by to0simple** [maxGraph/maxgraph#353]
An error occurred in encode while looking at example（https://github.com/maxGraph/maxGraph/blob/v0.5.0/packages/html/stories/JsonData.stories.js）

![image](https://github.com/maxGraph/maxGraph/assets/23261843/7bc86062-03e7-4c96-8a63-a051aceec269)

The console reported an error when I clicked the button

![image](https://github.com/maxGraph/maxGraph/assets/23261843/b53ad5dc-eeda-4cba-9015-08e36b188b71)

**Comment by tbouffard** [comment]
Hi,
A lot of errors related to Codec has been fixed in https://github.com/maxGraph/maxGraph/releases/tag/v0.6.0 and https://github.com/maxGraph/maxGraph/releases/tag/v0.7.0
The JsonData story has a bug in v0.8.0: it generates `Uncaught InternalError: too much recursion`
This should be fixed by #350

**Comment by to0simple** [comment]
> Hi, A lot of errors related to Codec has been fixed in https://github.com/maxGraph/maxGraph/releases/tag/v0.6.0 and https://github.com/maxGraph/maxGraph/releases/tag/v0.7.0 The JsonData story has a bug in v0.8.0: it generates `Uncaught InternalError: too much recursion` This should be fixed by #350

Thanks for your reply, I see you merged the code, let me try it

**Comment by to0simple** [comment]
I have tried, and the problem has been solved.
