### ISSUE TITLE
When the replication function is used, the “restoreClone ”method is not invoked as expected.

### ISSUE THREAD

**Issue by Duoladuola** [maxGraph/maxgraph#355]
The method is defined as follows:
![image](https://github.com/maxGraph/maxGraph/assets/56530965/cc3f627b-abf7-4f24-9167-fce8b4ce44bf)
The method is invoked as follows（Is there a call missing here?）:
![image](https://github.com/maxGraph/maxGraph/assets/56530965/a119535c-f8f6-4256-88cb-cd19ca84c180)
Or remove one layer of the arrow function（This can also solve the problem that the EDGE cannot be copied.）:
![image](https://github.com/maxGraph/maxGraph/assets/56530965/aa3a6ef3-59a2-4ce0-a9f2-7828e6039336)

**Comment by tbouffard** [comment]
Hi @Duoladuola 
I don't understand the current description of this issue
Are you having some issue when using the 2 functions? if so, can you provide more details and/or ways to reproduce a problem?

Are you saying that according to you, the signature of the 2 functions is wrong:
- https://github.com/maxGraph/maxGraph/blob/be73a203c92049ef85eb261bdf5e8eb1b0757313/packages/core/src/util/cellArrayUtils.ts#L122-L125
- https://github.com/maxGraph/maxGraph/blob/be73a203c92049ef85eb261bdf5e8eb1b0757313/packages/core/src/util/cellArrayUtils.ts#L171-L173

Thanks

**Comment by Duoladuola** [comment]
> Hi @Duoladuola I don't understand the current description of this issue Are you having some issue when using the 2 functions? if so, can you provide more details and/or ways to reproduce a problem?
> 
> Are you saying that according to you, the signature of the 2 functions is wrong:
> 
> * https://github.com/maxGraph/maxGraph/blob/be73a203c92049ef85eb261bdf5e8eb1b0757313/packages/core/src/util/cellArrayUtils.ts#L122-L125
> * https://github.com/maxGraph/maxGraph/blob/be73a203c92049ef85eb261bdf5e8eb1b0757313/packages/core/src/util/cellArrayUtils.ts#L171-L173
 
Thanks for the replies. "cloneCells" is correct, the "restoreClone" two-tier arrow function is problematic. It is called to return a function, not to actually execute it.
![image](https://github.com/maxGraph/maxGraph/assets/56530965/5fdfdc31-6e72-493d-8d2e-0703743e893c)
![image](https://github.com/maxGraph/maxGraph/assets/56530965/4de5ce1c-e193-4923-8e73-f91057a68861)

**Comment by Duoladuola** [comment]
![image](https://github.com/maxGraph/maxGraph/assets/56530965/d06a5682-7de0-4b6b-a149-f6b48c244dd2)

**Comment by Duoladuola** [comment]
![image](https://github.com/maxGraph/maxGraph/assets/56530965/742b3355-e388-4814-b97e-4185f9aa59a1)
I checked the "restoreClone" of mxGraph and there is NO two-layer arrow function defined.

**Comment by Duoladuola** [comment]
![image](https://github.com/maxGraph/maxGraph/assets/56530965/0737ee51-6713-429d-b2dd-dab5403c7e0d)

**Comment by LZTWilliam** [comment]
> Hi @Duoladuola I don't understand the current description of this issue Are you having some issue when using the 2 functions? if so, can you provide more details and/or ways to reproduce a problem?
> 
> Are you saying that according to you, the signature of the 2 functions is wrong:
> 
> * https://github.com/maxGraph/maxGraph/blob/be73a203c92049ef85eb261bdf5e8eb1b0757313/packages/core/src/util/cellArrayUtils.ts#L122-L125
> * https://github.com/maxGraph/maxGraph/blob/be73a203c92049ef85eb261bdf5e8eb1b0757313/packages/core/src/util/cellArrayUtils.ts#L171-L173
> 
> Thanks

I believe @Duoladuola means that the function `restoreClone` should be invoked as follow
```javascript
restoreClone(clone.getChildAt(i), cell.gethildAt(i), mapping)(cells) // should be invoked twice
```
while in `cloneCells`(and `restoreClone` it self) it's invoked as follow. This invocation only returns another function, and doesn't actually insert edges between cells.
> * https://github.com/maxGraph/maxGraph/blob/be73a203c92049ef85eb261bdf5e8eb1b0757313/packages/core/src/util/cellArrayUtils.ts#L132-L134

However, parameter `cells` is never used in `restoreClone`, is it necessary to currying this function?
```javascript
// Maybe change the function as follow?
export const restoreClone =
  (clone: Cell, cell: Cell, mapping: any) => {
    const source = cell.getTerminal(true);
    ...
  }
```

**Comment by tbouffard** [comment]
Thanks @Duoladuola and @LZTWilliam for the additional information.
Your analysis seems legit, for both `cloneCells` and `restoreClone`
This seems to be a problem which has been introduced during the migration from mxGraph. The original code mxGraph is here: https://github.com/jgraph/mxgraph/blob/v4.2.2/javascript/src/js/model/mxGraphModel.js#L2265 

If someone want to provide a Pull Request to fix the issue (try to add automatic tests please), feel free to open one.

**Note**: the signature of the `getOpposites` function seems to have the same problem.

**Comment by tbouffard** [comment]
ℹ️ I'm going to work on it and hope to include a fix in the next version.

**Comment by tbouffard** [comment]
ℹ️ I've merged a fix that will be available in the next version I plan to release soon.
cc @Duoladuola @LZTWilliam

**Comment by tbouffard** [comment]
ℹ️ The fix is available in https://github.com/maxGraph/maxGraph/releases/tag/v0.11.0
