### ISSUE TITLE
Older versions of mxPoint do not decode successfully

### ISSUE THREAD

**Issue by Duoladuola** [maxGraph/maxgraph#356]
The codec registration method is compatible with mxCell, mxGeometry, and mxGraphModel, but is not compatible with mxPoint.

  // mxGraph support
        CodecRegistry.addAlias('mxGraphModel', 'GraphDataModel');
        CodecRegistry.register(new mxCellCodec(), false);
        CodecRegistry.register(new mxGeometryCodec(), false);

Does it need to add compatibility support for mxPoint?like fellows：
// decode support for mxPoint
maxgraph.CodecRegistry.addAlias('mxPoint', 'Point');

**Comment by tbouffard** [comment]
Hi @Duoladuola
Do you have an example of an XML that demonstrates a problem or a repository to reproduce an issue?

Currently, only XML produced by mxGraph containing Model data can be imported.
There are several tests that shows that the import is working: https://github.com/maxGraph/maxGraph/blob/v0.8.0/packages/core/__tests__/serialization/serialization.xml.mxGraph.test.ts
There are also several Stories that load mxGraph XML model data, for example: https://github.com/maxGraph/maxGraph/blob/be73a203c92049ef85eb261bdf5e8eb1b0757313/packages/html/stories/Codec.stories.ts or https://github.com/maxGraph/maxGraph/blob/be73a203c92049ef85eb261bdf5e8eb1b0757313/packages/html/stories/FileIO.stories.ts

Currently, the `mxGeometry.points` array of mxPoint  is managed in https://github.com/maxGraph/maxGraph/blob/v0.8.0/packages/core/src/serialization/codecs/mxGraph/mxGeometryCodec.ts#L31. So there is no need for a dedicated Codec to manage mxPoint.

**Comment by Duoladuola** [comment]
![image](https://github.com/maxGraph/maxGraph/assets/56530965/dbc6fd03-00cc-4cad-b7b0-98bed9f88a7d)
![image](https://github.com/maxGraph/maxGraph/assets/56530965/bcb82b3e-4868-46e4-829f-4003f84db7b5)

I  checked the tests, they didn't use "mxPoint".But the issue I proposed can be resolved by 
![image](https://github.com/maxGraph/maxGraph/assets/56530965/12cefae4-2898-4ca8-8e94-483ebdce360c)
,It won't get in the way of me.

**Comment by tbouffard** [comment]
Yes the tests do not include xml containing "mxPoint" nodes.
No use case involving such nodes was previously shared.

What I suggest you is to share a real mxgraph XML source in a text form to show the use case you are mentioning.
Without this data, this is hard to understand if this is valid situation.
Please share xml in a file or as text to let reproduce your use case.

**Comment by Duoladuola** [comment]
> Yes the tests do not include xml containing "mxPoint" nodes. No use case involving such nodes was previously shared.
> 
> What I suggest you is to share a real mxgraph XML source in a text form to show the use case you are mentioning. Without this data, this is hard to understand if this is valid situation. Please share xml in a file or as text to let reproduce your use case.

Thanks for the reply. This is a piece of xml from my work：
`<mxGraphModel>
  <root>
    <mxCell id="0"/>
    <mxCell id="1" parent="0"/>
    <mxCell id="3" value="Data" style="shape=Rectangle;borderRadius=8;labelWidth=120;verticalLabelPosition=middle;fillColor=#e9e4f8;fontColor=#000000;strokeColor=#e9e4f8;fontSize=12;resizable=0;rounded=1;imageAlign=left;imageVerticalAlign=middle;imageWidth=20;imageHeight=20;portColor=#8265E7;overflow=hidden;" parent="2" vertex="1" connectable="0">
      <mxGeometry width="158" height="32" relative="1" as="geometry">
        <mxPoint x="1" y="1" as="offset"/>
      </mxGeometry>
    </mxCell>
    <mxCell id="4" value="in" style="shape=Rectangle;fillColor=#DDDDDD;strokeColor=#8265E7;strokeSize=2;align=left;spacingLeft=15;spacingBottom=1;fontColor=#707070;" parent="2" vertex="1" type="input">
      <mxGeometry width="10" height="10" relative="1" as="geometry">
        <mxPoint x="14" y="43" as="offset"/>
      </mxGeometry>
    </mxCell>
    <mxCell id="5" value="out" style="shape=Rectangle;fillColor=#8265E7;strokeColor=#8265E7;strokeSize=2;align=right;spacingRight=15;spacingBottom=1;fontColor=#707070;verticalLabelPosition=middle;portStatus=unconnected;" parent="2" vertex="1" outputName="TRANSFORM_OUT" type="output">
      <mxGeometry x="1" y="0.0001" width="14" height="14" relative="1" as="geometry">
        <mxPoint x="-24.5" y="42" as="offset"/>
      </mxGeometry>
    </mxCell>
    <mxCell id="6" value="game" style="shape=label;strokeColor=#DDDDDD;fontColor=#707070;whiteSpace=wrap;overflow=width" parent="2" vertex="1" connectable="0" type="OperaNames">
      <mxGeometry x="0.05" y="0.6734693877551021" width="144" height="32" relative="1" as="geometry"/>
    </mxCell>
  </root>
</mxGraphModel>`

**Comment by tbouffard** [comment]
@Duoladuola thanks for the XML, this is now clearer.
The existing examples used in tests and stories are not using the geometry.offset which is defined as an `mxPoint` node in your example. That's probably why the support for mxPoint was missing.

I am preparing a PR for that which will include unit tests.

**Comment by tbouffard** [comment]
@Duoladuola the PR is #359 
It uses the alias you proposed in the description of this issue.

As discussed in the past we other contributors, we try to fix and add change for real use cases and also add automatic tests (or Stories when this is not possible to easily to automatic tests).
This is to improve the test coverage which is very low and avoid regressions.
That's why I was asking so many question and requesting an XML source showing the issue.
