### ISSUE TITLE
inconsistency in migration: removal of isAncestor and getParent in GraphModel

### ISSUE THREAD

**Issue by Duoladuola** [maxGraph/maxgraph#366]
In the old version, mxGraphModel contains the isAncestor function. In the new version, the isAncestor function is replaced by the isAncestor method in Cell.js. However, the input parameters are changed, causing inconsistency in migration.

### mxGraph4.2.2
![image](https://github.com/maxGraph/maxGraph/assets/56530965/6908167b-7ec6-4d79-9df7-fd64c36001d0)
### maxGraph0.8.0: The `GraphDataModel `does not contain the `isAncestor `function. Instead, the `isAncestor `function in the `Cell.js `is invoked.
![image](https://github.com/maxGraph/maxGraph/assets/56530965/b6763d86-3e7f-4cc0-a2f4-020ced2d6d36)

### mxGraph4.2.2
![image](https://github.com/maxGraph/maxGraph/assets/56530965/6883e6fd-93c2-4c61-8afc-ff860964ef40)
### maxGraph0.8.0
![image](https://github.com/maxGraph/maxGraph/assets/56530965/054fc91d-6f0d-4498-95dc-da105c1b132b)

They are not serious problem. I can modify my code accordingly.

**Comment by tbouffard** [comment]
Hello @Duoladuola 

The change was made voluntarily during the migration of the mxGraph code.
For now, I've created  #550  to try to improve the migration documentation about the removal of the 2 methods.  The `getParent` method has already been mentioned.

As stated in https://github.com/maxGraph/maxGraph/discussions/179#discussioncomment-5388614, the removal of these `GraphDataModel` methods was done to simplify the code base, but it could limit extension capabilities.
If this is the case, create a dedicated question explaining the specific limitations that the current maxGraph code introduces.
