### ISSUE TITLE
What is the version of the jscolor.js lib used in examples?

### ISSUE THREAD

**Issue by amonga67** [maxGraph/maxGraph#4]
Hello,
Does mxgraph use jscolor ?
I dont see any call to this plugin, instead there is a class called "mxJSColor" in "mxgraph/javascript/examples/grapheditor/www/jscolor/jscolor.js"
My question is , if i use mxgraph which is under Apache License 2.0 , does this licence still apply to your custom jscolor or do I have to purchase a jscolor licence in order to use it with mxgraph ?

**Comment by davidjgraph** [comment]
The version of jscolor used is 1.3.13. That was released under the LGPL.

**Comment by tbouffard** [comment]
Answered, so closing.
