### ISSUE TITLE
[BUG] In Handles and Stencils stories, the rotation handle is always located on the right of the vertex

### ISSUE THREAD

**Issue by tbouffard** [maxGraph/maxgraph#482]
### Describe the bug
**Note: this is visible in Stories but the problem probably occurs in all applications.**

The "rotation handle" is always located on the right of the vertex, even after having done some rotation.
So, on a next rotation, the initial orientation of the preview does not match the current orientation of the vertex. 

### To Reproduce

For the `Handles` story, see https://maxgraph.github.io/maxGraph/demo/?path=/story/layouts-handles--default or run the story locally.
Same for the `Stencils` story.

### Expected behavior

In mxGraph examples

### Handles

https://jgraph.github.io/mxgraph/javascript/examples/handles.html

https://github.com/maxGraph/maxGraph/assets/27200110/e0f53aa3-6d85-415a-b2d3-34d4c908bd0a

### Stencils

https://jgraph.github.io/mxgraph/javascript/examples/stencils.html

https://github.com/maxGraph/maxGraph/assets/27200110/a89683d9-2e9a-422c-b6eb-7a7cb3466249

### Handles

https://github.com/maxGraph/maxGraph/assets/27200110/be63c6ce-0761-4487-8226-2b161807b33e

### Stencils

https://github.com/maxGraph/maxGraph/assets/27200110/95c79b3d-3608-4d23-9cc6-50699a93af17

### Environment
- Desktop
- OS and version: Ubuntu 20.04
- Browser and version: Firefox 126.0.1, Chrome 126.0.6478.126
- commit 50eb99b with the commit of #480

**Comment by sunnyTaner** [comment]
I also encountered this problem.

**Comment by HalilFocic** [comment]
@tbouffard I wanna try to fix this, just wondering if the handle should go above the rectangle like in mX graph or do we want to keep it inside. I think this this will make much difference but would like to know your opinion.

**Comment by HalilFocic** [comment]
This seems to work fine at first glance but I will have to check again.I tweaked one thing that I'm not 100% certain what is does but basically regular sizers were using proper alpha based on rotation of the object while rotation sizer used total different one even tho logic should be the same. I will make PR tomorrow morning regarding this 

https://github.com/user-attachments/assets/ff4ede56-c4f2-41eb-8525-a272240eed7a

**Comment by tbouffard** [comment]
Hi @HalilFocic great to hear you are working on this. I have assigned you to this issue.
About the handle position, I suggest to keep the mxGraph behavior to restore the feature.
It will be possible in the future to add options to change the existing behavior.
