### ISSUE TITLE
[FEAT]How can I use  graph.zoomIn();

### ISSUE THREAD

**Issue by pccai** [maxGraph/maxgraph#491]
`  buttons.appendChild(DomHelpers.button('+', function () {
    graph.zoomIn();
  }));
  buttons.appendChild(DomHelpers.button('-', function () {
    graph.zoomOut();
  }));`

v0.12.0

**Comment by tbouffard** [comment]
Hi @pccai 
Can you provide more details about your question?
What are you trying to achieve,  what is not working, what information is missing?

I guess the code extract in the description is coming from the storybook example.
What is wrong with this code in your use case?

**Comment by pccai** [comment]
I want to zoomIn or zoomOut the graph via program

**Comment by tbouffard** [comment]
Using graph.zoomIn() or graph.zoomOut() is known to work.
Aren't they working for you?

**Comment by tbouffard** [comment]
No answer so closing for clearing the backlog.
Feel free to comment or create a new issue if you want to provide more details.
