### ISSUE TITLE
Partial convert mxGraph to es6 based on a provided codemod

### ISSUE THREAD

**Issue by CommunityMan** [maxGraph/maxGraph#5]
Based on the codemod provided by @adrianhdezm : https://github.com/adrianhdezm/mxgraph-codemod
regenerate a base es6 version of mxGraph from this repository sources and test it.

To run the codemod :
launch node on the index.js with the clone of this mxGraph repo in javascript dir in parameter : 
e.g. : node index.js /home/user/mxgraph-clone/javascript

I'm not yet sure if it is the correct procedure, @adrianhdezm could you confirm?

**Comment by ghost** [comment]
you could exec as below:

```
node index.js /home/user/mxgraph-clone/javascript/src
```

Please confirm the dir. you know, only dir 'src' should be transpiled.
And this is the start.

**Comment by CommunityMan** [comment]
Thanks @liyunhechn , indeed it is working well launching it directly on src.
I'll now check every classes generated for the missing part and add the imports

**Comment by CommunityMan** [comment]
Hi @coclav, no sure what is the flow here, but could I have access to the repo to push the work on this issue into a dedicated branch?

**Comment by jgadsden** [comment]
I can do this for you @CommunityMan - what  branch name is best?

**Comment by tbouffard** [comment]
IMHO we can close this issue. We already have a conversion done with #16 and already available in the `development` branch.

**Comment by jgadsden** [comment]
@tbouffard I agree - do you want to go ahead and close this issue #5

**Comment by tbouffard** [comment]
So closing as @jgadsden agreed 😸
