### ISSUE TITLE
Is the typescript version currently available?

### ISSUE THREAD

**Issue by hungtcs** [maxGraph/maxGraph#53]
Hi, 
I am recently wanted to create a demo project using maxgraph, but I didn't find the relevant guidance. I noticed that you guys are using typescript to refactoring, this is really an exciting move.
If I want to start a new project using typescript, are there any suggestions here?
thanks 😄 !

**Comment by tbouffard** [comment]
Hi @hungtcs ,
AFAIK, the TS port is a work in progress which is in a very unstable state
- discussion about the status of the TS implementation #51
- issue leading the TS effort #44 
- a work/experiment #42

**Comment by tbouffard** [comment]
Closing, if you nee more information, please open a new Discussion in https://github.com/maxGraph/maxGraph/discussions
