### ISSUE TITLE
[BUG] PageBreak Story: "Print" does not work.

### ISSUE THREAD

**Issue by reuse-ay** [maxGraph/maxgraph#535]
### Describe the bug
In page break story, "Print" button does not work.

### To Reproduce
1. Go to [story](https://maxgraph.github.io/maxGraph/demo/?path=/story/printing-pagebreaks--default).
2. Click on 'Print'.
(Nothing happens.)

### Expected behavior
After click, a new tab will be opened and I can see preview.
See [mxGraph example](https://jgraph.github.io/mxgraph/javascript/examples/pagebreaks.html).

### Additional context
Error in console:
![スクリーンショット 2024-09-18 090222](https://github.com/user-attachments/assets/1fd03a02-8599-4f83-a62f-aa8d79daa253)

**Comment by tbouffard** [comment]
I confirm the issue, the `PrintPreview` import is missing in the story. See https://github.com/maxGraph/maxGraph/blob/d3f6c50967f69acecda058de6a7217b8cb3f304f/packages/html/stories/PageBreaks.stories.js

If someone wants to contribute a fix, feel free to post a comment. In this case, consider migrating the story to TypeScript to ease the future maintenance (this easily detects missing imports for instance).

Be aware that adding the import probably won't make the `PrintPreview` work. In #532, there was the same issue. After having added the import, the "print preview" button now works but it opens a new empty tab.
Some additional work may be required. 

IMHO, it is valid to provide a PR that fix the missing import (and other detected issues during development) even if all features of the story are not working. This is already a nice improvement.

**Comment by tbouffard** [comment]
#537 fix the imports. The "Print" button now opens a new tab, but it doesn't show the vertices or edges.
https://github.com/maxGraph/maxGraph/pull/88/commits/4ddbdf55bac99c4cdc7e03ff3722026742782eaa may provide some ideas for a more complete fix (I didn't check this commit in details).

**Comment by reuse-ay** [comment]
Additionally, compared to mxgraph,

-  I noticed that when I open a new tab, the background is not colored. 
- It seems that the title has not been set.

**Comment by tbouffard** [comment]
ℹ I am going to give a try to the fix of TemporaryCellStates seen in https://github.com/maxGraph/maxGraph/pull/88/commits/4ddbdf55bac99c4cdc7e03ff3722026742782eaa

**Comment by tbouffard** [comment]
@reuse-ay #546 should fix most of the remaining problems.
