### ISSUE TITLE
[BUG]Editing story: can't edit value.

### ISSUE THREAD

**Issue by reuse-ay** [maxGraph/maxgraph#544]
### Describe the bug
In editing story, I can't edit cell values.

### To Reproduce
1. Go to [editing story](https://maxgraph.github.io/maxGraph/demo/?path=/story/editing-editing--default)
2. Double click on "First value" or "Second value". (Nothing happens)

### Expected behavior
Double-click the text to make it editable.
[mxgraph example](https://jgraph.github.io/mxgraph/javascript/examples/editing.html)

maxgraph@0.13.0

### Additional context
I've used editing in my personal projects, so perhaps it's just a problem with the story.

**Comment by reuse-ay** [comment]
In story, `MyCustomGraph` (extends `Graph`) .`getLabel` return `HTMLTableElement`, but in `Graph`, return of `getLabel` should be string. So an error occured. To fix this, a number of changes are needed.

**Comment by tbouffard** [comment]
Hi I reproduced the problem.

In mxGraph, mxGraph.getLabel returns string | Node (https://github.com/typed-mxgraph/typed-mxgraph/blob/v1.0.8/lib/view/mxGraph.d.ts#L2883)

In maxGraph, the signature of Graph.getLabel has been simplified, probably by mistake during the migration https://github.com/maxGraph/maxGraph/blob/c4b35906115721816d1f5101883530b935264354/packages/core/src/view/mixins/LabelMixin.type.ts#L74

**Comment by tbouffard** [comment]
I have seen the same problem in the `OrgChart` story, see #532
