### ISSUE TITLE
[BUG] getDefaultPlugins not exported

### ISSUE THREAD

**Issue by jeromecc** [maxGraph/maxgraph#552]
getDefaultPlugins is not exported from packages/core/src/index.ts which breaks most examples

**Comment by tbouffard** [comment]
Hi @jeromecc 
`getDefaultPlugins` is not exported directly in packages/core/src/index.ts, but through `export * from './view/plugins';`. See https://github.com/maxGraph/maxGraph/blob/v0.13.0/packages/core/src/index.ts#L21

`getDefaultPlugins` is imported in various place of the maxgraph repository using a locally built npm package:
- the Stories (for example in https://github.com/maxGraph/maxGraph/blob/v0.13.0/packages/html/stories/ContextIcons.stories.ts#L30)
- ts-example (built with vitejs): https://github.com/maxGraph/maxGraph/blob/v0.13.0/packages/ts-example/src/main.ts#L22
- js-example (built with webpack): https://github.com/maxGraph/maxGraph/blob/v0.13.0/packages/js-example/src/index.js#L22

It is also used in https://github.com/maxGraph/maxgraph-integration-examples where it uses the npm package in the same way that any application would use it, and there is no import problem. See https://github.com/maxGraph/maxgraph-integration-examples/pull/148/files

 
So, the export seems correct.

Which `maxGraph` version are you using? if you use a version older than 0.13.0, the function doesn't exist, see https://github.com/maxGraph/maxGraph/releases/tag/v0.13.0

> [!NOTE]
> The next time you open an issue, please use the related issue template (in this case the "bug" template) and please indicate the version information, which will facilitate diagnosis.

**Comment by tbouffard** [comment]
Closing as there is no answer from the requester after almost 3 weeks.
Feel free to reopen if you have more information to share.
