### ISSUE TITLE
Hope for a new release named maxgraph

### ISSUE THREAD

**Issue by lalicw** [maxGraph/maxgraph#56]
hope for a new release named maxgraph, available in npmjs.

will this repo keep only javascript mxClient ? 

as discussion https://github.com/maxGraph/maxGraph/discussions/19 mentioned, can i make a pr to remove other code?

**Comment by tbouffard** [comment]
Hi @lalicw 
The `development` branch already contains the change: only javascript code.

**Comment by lalicw** [comment]
oh, that's great, hope for a new npm package now!

**Comment by Seebiscuit** [comment]
Hi, folks any update on when maxgraph will hit alpha/beta?

**Comment by tbouffard** [comment]
@Seebiscuit hi, as mentioned in https://github.com/maxGraph/maxGraph/discussions/41#discussioncomment-1333274, the maxgraph project is looking for testers. There is currently no plan to release anything prior we receive feedback.
Please check #51. You can build the project, play with the examples.

If you think that releasing a preversion can serve the testing purpose, please open a new [discussion](https://github.com/maxGraph/maxGraph/discussions) to see how we can manage it.

**Comment by rivenww** [comment]
Hi, for months I found out that this repo has changed much. 
So is there anyway to build the code in development branch to a local npm module? or is the branch just not a release and still being developed?
And what can I do for this repo ? XD

**Comment by tbouffard** [comment]
Please have a look at #64 for the current project status

**Comment by tbouffard** [comment]
I am closing this issue. We have pending discussions about the release topic in #89 and #92. Once they will be handled, we will be able to do a release.
