### ISSUE TITLE
XMLHttpRequest Deprecated warning

### ISSUE THREAD

**Issue by overpolish** [maxGraph/maxgraph#57]
Using the library gives me a deprecation warning of for XMLHttpRequest and additionally errors about not being able to open **graph.txt**, **editor.txt** and **common.css**. I do not want to add these files but want to remove the error and handle the deprecation issue.

Any workarounds? This happens on package load before any of my code is executed.

**Comment by tbouffard** [comment]
Hi, are you using mxgraph@4.2.2 or the upcoming `maxGraph` development version?
For mxGraph, if you don't want to use any mxGraph resources, you should set the following globals to `false`:   `mxLoadResources` and `mxLoadStylesheets`.

**Comment by overpolish** [comment]
Hi, thanks for the response it has helped solve this issue. Is there a way to install maxGraph using npm (or into node_modules folder) or is this repo not currently production ready (I notice you mention it is still the development version).

**Comment by tbouffard** [comment]
maxGraph is currently not published on npmjs, see #51 for a status.
Closing as the original problem is solved.
