### ISSUE TITLE
Graph doesn't fire 'Connect' event.

### ISSUE THREAD

**Issue by jaki102** [maxGraph/maxgraph#599]
Hi!
I have an issue with `InternalEvent.CONNECT`.
I would like to do some actions after connect two cells. I try to do it on `connect` event but unfortunately event does't fire. I try to do it by:
```
this.graph.getSelectionModel().addListener(InternalEvent.CONNECT, (sender, evt) => {
     // do some actions
})
```
Do you have any suggestions what I am doing wrong?

**Comment by HalilFocic** [comment]
Could you try this:

```javascript
graph.addListener(
    InternalEvent.CELL_CONNECTED,
    (_sender: Graph, evt: EventObject) => {
      const sourceId = evt.properties?.edge.source?.id;
      const targetId = evt.properties?.edge.target?.id;
      const edgeId = evt.properties?.edge.id;
      console.log("connected ",sourceId,targetId);
    }
  );
```

I am on mobile so code might looked scuffed, but this worked for me on my project

**Comment by jaki102** [comment]
It seems to be work! @HalilFocic thank you so much for your help!
