### ISSUE TITLE
Running npm command failed 

### ISSUE THREAD

**Issue by cd-yang** [maxGraph/maxgraph#61]
Branch: **development**

```sh
$ npm run dev
```

and select `@mxgraph/core`.

### Expected Behavior
Run core package successfully

### Current Behavior
Executing command got error as follows,
> Running 'npx lerna run dev --stream --scope @maxgraph/core'...
lerna notice cli v4.0.0
lerna notice filter including "@maxgraph/core"
lerna info filter [ '@maxgraph/core' ]
lerna info Executing command in 1 package: "npm run dev"
@maxgraph/core: > @maxgraph/core@1.0.0 dev C:\Users\SE-YCD\Desktop\maxGraph\packages\core
@maxgraph/core: > webpack --watch --mode=development
@maxgraph/core: asset maxgraph.js 8.33 MiB [compared for emit] (name: main)
@maxgraph/core: runtime modules 670 bytes 3 modules
@maxgraph/core: modules by path ./src/view/ 1.94 MiB 125 modules
@maxgraph/core: modules by path ./src/util/ 563 KiB 46 modules
@maxgraph/core: modules by path ./src/editor/*.js 114 KiB
@maxgraph/core:   ./src/editor/mxDefaultKeyHandler.js 4.43 KiB [built] [code generated]
@maxgraph/core:   ./src/editor/mxDefaultPopupMenu.js 11.6 KiB [built] [code generated]
@maxgraph/core:   ./src/editor/mxDefaultToolbar.js 17 KiB [built] [code generated]
@maxgraph/core:   ./src/editor/mxEditor.js 81 KiB [built] [code generated]
@maxgraph/core: ./src/index.ts 13 KiB [built] [code generated]
@maxgraph/core: ./src/mxClient.js 14.3 KiB [built] [code generated]
@maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src\util\Dictionary.ts -> src\util\ObjectIdentity.ts -> src\util\Utils.ts -> src\util\Dictionary.ts
@maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src\util\ObjectIdentity.ts -> src\util\Utils.ts -> src\util\Dictionary.ts -> src\util\ObjectIdentity.ts
@maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src\util\Resources.js -> src\util\network\mxXmlRequest.js -> src\util\XmlUtils.js -> src\util\serialization\mxCodec.js -> src\util\serialization\mxCodecRegistry.js -> src\util\serialization\mxObjectCodec.js -> src\util\gui\mxLog.js -> src\util\gui\mxWindow.js -> src\util\Resources.js
@maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src\util\Utils.ts -> src\util\Dictionary.ts -> src\util\ObjectIdentity.ts -> src\util\Utils.ts
@maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src\util\XmlUtils.js -> src\util\serialization\mxCodec.js -> src\util\serialization\mxCodecRegistry.js -> src\util\serialization\mxObjectCodec.js -> src\util\gui\mxLog.js -> src\util\gui\mxWindow.js -> src\util\Resources.js -> src\util\network\mxXmlRequest.js -> src\util\XmlUtils.js
@maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src\util\gui\mxLog.js -> src\util\gui\mxWindow.js -> src\util\Resources.js -> src\util\network\mxXmlRequest.js -> src\util\XmlUtils.js -> src\util\serialization\mxCodec.js -> src\util\serialization\mxCodecRegistry.js -> src\util\serialization\mxObjectCodec.js -> src\util\gui\mxLog.js
@maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src\util\gui\mxWindow.js -> src\util\Resources.js -> src\util\network\mxXmlRequest.js -> src\util\XmlUtils.js -> src\util\serialization\mxCodec.js -> src\util\serialization\mxCodecRegistry.js -> src\util\serialization\mxObjectCodec.js -> src\util\gui\mxLog.js -> src\util\gui\mxWindow.js
@maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src\util\network\mxXmlRequest.js -> src\util\XmlUtils.js -> src\util\serialization\mxCodec.js -> src\util\serialization\mxCodecRegistry.js -> src\util\serialization\mxObjectCodec.js -> src\util\gui\mxLog.js -> src\util\gui\mxWindow.js -> src\util\Resources.js -> src\util\network\mxXmlRequest.js
@maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src\util\serialization\mxCodec.js -> src\util\serialization\mxCodecRegistry.js -> src\util\serialization\mxObjectCodec.js -> src\util\gui\mxLog.js -> src\util\gui\mxWindow.js -> src\util\Resources.js -> src\util\network\mxXmlRequest.js -> src\util\XmlUtils.js -> src\util\serialization\mxCodec.js
@maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src\util\serialization\mxCodecRegistry.js -> src\util\serialization\mxObjectCodec.js -> src\util\gui\mxLog.js -> src\util\gui\mxWindow.js -> src\util\Resources.js -> src\util\network\mxXmlRequest.js -> src\util\XmlUtils.js -> src\util\serialization\mxCodec.js -> src\util\serialization\mxCodecRegistry.js
@maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src\util\serialization\mxObjectCodec.js -> src\util\gui\mxLog.js -> src\util\gui\mxWindow.js -> src\util\Resources.js -> src\util\network\mxXmlRequest.js -> src\util\XmlUtils.js -> src\util\serialization\mxCodec.js -> src\util\serialization\mxCodecRegistry.js -> src\util\serialization\mxObjectCodec.js
@maxgraph/core: webpack 5.32.0 compiled with 11 errors in 16018 ms

### More info

```sh
$ webpack -v
webpack 5.32.0
webpack-cli 4.6.0
$ node -v
v14.16.1
$ npm -v
6.14.12
```

Execute

```sh
$ npm run dev
```

and select `@mxgraph/html`. Storybook works fine.

**Comment by tbouffard** [comment]
I also see this error, I guess this is because the https://www.npmjs.com/package/circular-dependency-plugin is enabled in the webpack config.
I remember that @mcyph and @junsikshim were working on removing circular dependencies. The errors we see here probably hightlight the remaining work on that topic.

**Comment by junsikshim** [comment]
What @tbouffard said is correct. There were too many circular dependencies in the original code, so I added the plugin to see where they exist. Some of them are very hard to take care of without restructuring many components :(

Even though the messages indicate ERROR, I think they are more like warnings. (The components seem to work fine.)

**Comment by cd-yang** [comment]
I dig into some code, and find that many circular dependencies are caused by network relating functions.
e.g.
> @maxgraph/core: ERROR in Circular dependency detected:
@maxgraph/core: src/util/network/mxXmlRequest.js -> src/util/XmlUtils.js -> src/util/serialization/mxCodec.js -> src/util/serialization/mxCodecRegistry.js -> src/util/serialization/mxObjectCodec.js -> src/util/network/mxXmlRequest.js

In the above error message, **mxObjectCodec.js** is infrustructure level code. However it depends on **mxXmlRequest.js**.

If we are going to make maxGraph more **client side** lib, mxGraph network codes might be removed.

**Comment by tbouffard** [comment]
@cd-yang I agree with you about mxXmlRequest, this should be out of the scope of maxGraph and alternatives exist (vanilla fetch, other lib).
We already mentioned this removal in the past https://github.com/maxGraph/maxGraph/issues/8#issuecomment-811561176

**Comment by mcyph** [comment]
I've fixed a number of recursive import problems and pushed to `dev`. Please try it out and let me know if you have any more issues.

I haven't yet removed the `mxXmlRequest` module but I think doing that along with the resources modules is likely the best option going forwards.

**Comment by cd-yang** [comment]
@mcyph Thanks for your work. No more circular dependencies on my machine.
