### ISSUE TITLE
[Question] Useful testing review

### ISSUE THREAD

**Issue by shakeZSL** [maxGraph/maxgraph#73]
Hi,

I tested some of the examples on the weekend. A lot seems to work already, huge thank you for all your work!
I guess you are already aware of this stuff, but i still wanted to list some things I noticed in the examples:

1. Anchors: ConnectionPoints not showing --> #77
2. Collaps: Doesn't work --> #385
3. ContextIcons: No icons showing --> #413
4. Swimlanes: Empty example --> #156
5. Validation: There was no highlighting and it started to lag pretty heavy, when i hovered over the targetElements (lots of errors in the browser console) --> see  #362
6. UserObject: Vertex not showing --> #350
...

Tried to adjust the Toolbar example:

- Connections can be created/moved inside of shapes (i dont think that is intended?)
- ConnectionHandler suggests method "createElement()", i believe it should be "createTarget()"?

Dont know if that is of any help, but atleast wanted to report what i found. 
I am unsure if i can really test in the future, but it might be possible. 
If so is there any guide how to test this repo in a good way and how to report them so that it is actually useful to you guys?

Thanks

**Comment by mcyph** [comment]
Thanks for reporting! There's been so much to do we've basically been working on things as they come up, but especially going forwards we should be tracking what is/isn't working better and I think this is a great starting point. There's still some left to be done in the `stashed` folder which don't show in storybook, I started work on these last weekend but still a fair amount to do, especially for the editor example.

**Comment by tbouffard** [comment]
@shakeZSL thanks for reporting.
As a general advice, can you please mention the browser (name and version), the OS, Desktop or mobile, node version, ...? This probably may not be relevant here but giving a lot of context help investigating.
In the future, I guess we will setup an issue template to remind this at issue creation.

**Comment by junsikshim** [comment]
Currently, I'm working on '1. Anchors' example.
I'm still kind of busy so I'll focus on debugging small problems for now.

**Comment by gelvidge** [comment]
I'm currently going through the examples and fixing bugs.  Most problems are due to the example html code needing to be updated to reflect the updated codebase.  There are a few bugs introduced into the core codebase (e.g. changes made in null evaluations).  
I've fixed all the examples listed above but there are others also.  I've almost gone through all examples - will submit a PR when finished

**Comment by tbouffard** [comment]
ℹ️ The Toolbar story has been improved with various PR
- #230
- #340
- #390
- #412
