### ISSUE TITLE
`TouchEvent is not defined` error with Firefox Desktop / `Can't find variable: TouchEvent` error with Safari Desktop

### ISSUE THREAD

**Issue by tbouffard** [maxGraph/maxgraph#76]
**Environment**
- Firefox Desktop 95.0.1 and 96.0
- Ubuntu 20.04.3 LTS
- Node v16.13.1 npm 8.3.0
- commit 3494d0fb

The error is triggered when clicking on the Canvas or when selecting a shape or panning the graph as shown in the following video 👇

https://user-images.githubusercontent.com/27200110/150548100-938cd5b1-0480-4f0f-a131-b7c836ff61e9.mp4

```
Uncaught ReferenceError: TouchEvent is not defined
    consume InternalMouseEvent.ts:180
    consumeMouseEvent SelectionHandler.ts:544
    mouseUp SelectionHandler.ts:1462
    fireMouseEvent EventsMixin.ts:998
    installListeners CellRenderer.ts:788
```

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1693172. It seems there is no issue when touch simulation is enabled (which is disabled by default on Desktop) or a touch device is detected.
Possible fix: https://stackoverflow.com/questions/27313488/touchevent-not-working-in-firefox-and-other-website-browser#32882849

**Comment by zhangbiggs** [comment]
## stack trace please
<img width="461" alt="Screen Shot 2022-10-19 at 15 14 51" src="https://user-images.githubusercontent.com/13499245/196622168-c9ee0050-f24b-4a3b-bf5c-2f09f53f3538.png">

```js
[Error] ReferenceError: Can't find variable: TouchEvent
	consume (InternalMouseEvent.ts:58:87)
	mouseDown (RubberBandHandler.ts:79)
	fireMouseEvent (EventsMixin.ts:355)
	(anonymous function) (GraphView.ts:1107)
```

## reason
This recent commit broke usage in Safari and Firefox
https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent

In the desktop version, you should detect mouseEvent first and then TouchEvent, may be same as Firefox
aka，it can work as well as  iPad and iPhone safari

**Comment by zhangbiggs** [comment]
Thank you for doing this, I had the same idea as you before, refactoring the version of TypeScript, which is an interesting thing @tbouffard

**Comment by tbouffard** [comment]
@zhangbihua Thanks for the new information, I will test the PR #127 on Firefox Desktop as well, this seems promising
