### ISSUE TITLE
How to add ruler to graph

### ISSUE THREAD

**Issue by cd-yang** [maxGraph/maxgraph#81]
I'm trying to add ruler.
![graph-ruler](https://user-images.githubusercontent.com/17699525/160991123-fa2a658a-76f5-4e20-8091-127b34384583.png)

Is this possible or any solution?

**Comment by tbouffard** [comment]
Hi @cd-yang can you provide more details?
The elements on top and left of the image you attached seem not related to mxGraph/maxGraph directly. Are you looking for a way to make these elements interact with the graph?

**Comment by cd-yang** [comment]
Like visio, the ruler follows the movement when scrolling horizontally or vertically
![c88557728c7c0135d5ca694c79e57be](https://user-images.githubusercontent.com/17699525/161362610-8cfc45d5-e93d-4a3a-8bc7-15edda8186f9.png)

**Comment by tbouffard** [comment]
Thanks for the screenshot.

draw.io has a ruler feature: https://www.diagrams.net/doc/getting-started-editor. As it relies on mxGraph, I guess you can implement such feature by yourself. 
I have found this class that seems related to the ruler code https://github.com/jgraph/drawio/blob/v17.4.0/src/main/webapp/js/diagramly/mxRuler.js.
