### ISSUE TITLE
How to integrate maxGraph into my own project

### ISSUE THREAD

**Issue by cd-yang** [maxGraph/maxgraph#84]
Since there is no npm release now, should I use `npm link` to install maxGraph to my reactjs-based project.

**Comment by tbouffard** [comment]
hello
For now, I guess this is the only way.
I am also testing this on my side.

**Comment by tbouffard** [comment]
@cd-yang I have created #87 to start improving the npm package when built locally.
This is a work in progress and if you have time, I will be pleased to get your feedback.

**Comment by tbouffard** [comment]
#87 provides a way to test the npm package built locally.
I have also created a repository that demonstrates how to use the package with various bundlers: https://github.com/tbouffard/maxgraph-integration-examples
