### ISSUE TITLE
Whether Canvas Is Supported

### ISSUE THREAD

**Issue by asreday** [maxGraph/maxGraph#9]
If too many svg nodes cause frame freezing, how to optimize the problem?

**Comment by tbouffard** [comment]
mxGraph currently only generates SVG: https://jgraph.github.io/mxgraph/docs/manual.html#1.4 and is not designed to display a large amount of svg nodes.

**Comment by coclav** [comment]
what are you trying to do in the first place ?

**Comment by asreday** [comment]
> what are you trying to do in the first place ?

Do a large circuit diagram observation, about a few hundred plot points

**Comment by tbouffard** [comment]
@asreday please have a look at https://github.com/jgraph/mxgraph/issues/204 or https://github.com/jgraph/mxgraph/issues/265#issuecomment-654112783 to get more insights about the number of nodes `mxGraph` can currently displays.

**Comment by tbouffard** [comment]
A new discussion on this topic has just begun in #180.

**Comment by tbouffard** [comment]
Closing this issue as duplicate of #180.
